name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_NAME: pybrave
  DOCKERHUB_REPO: wybioinfo/pybrave
  ACR_REPO: registry.cn-hangzhou.aliyuncs.com/wybioinfo/pybrave

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Login to Aliyun Container Registry
      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      # Build image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # Tag and push to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker tag $IMAGE_NAME:latest $DOCKERHUB_REPO:latest
          docker push $DOCKERHUB_REPO:latest

      # Tag and push to Aliyun ACR
      - name: Push to Aliyun ACR
        run: |
          docker tag $IMAGE_NAME:latest $ACR_REPO:latest
          docker push $ACR_REPO:latest
